export const font_family = [
  { label: "Arial", value: "Arial" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Noto Sans", value: "Noto Sans" },
  { label: "Touche Semibold", value: "Touche Semibold" },
  { label: "Roboto", value: "Roboto" },
  { label: "Roboto Mono", value: "Roboto Mono" },
  { label: "Helvetica", value: "Helvetica" },
  { label: "Verdana", value: "Verdana" },
  { label: "Noto Sans CJK JP", value: "Noto Sans CJK JP" },
  { label: "Noto Naskh Arabic", value: "Noto Naskh Arabic" },
  { label: "Noto Sans Hebrew", value: "Noto Sans Hebrew" },
  { label: "Noto Sans Thai", value: "Noto Sans Thai" },
  { label: "Noto Sans Devanagari", value: "Noto Sans Devanagari" },
  { label: "Noto Sans Tamil", value: "Noto Sans Tamil" },
  { label: "Noto Sans Telugu", value: "Noto Sans Telugu" },
];
