export const font_family = [
  { label: "Arial", value: "Arial" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Helvetica", value: "Helvetica" },
  { label: "Verdana", value: "Verdana" },
  { label: "Roboto", value: "Roboto" },
  { label: "Roboto Mono", value: "Roboto Mono" },
  { label: "Noto Sans", value: "Noto Sans" },
  { label: "Noto Sans Japanese", value: "Noto Sans JP" },
  { label: "Noto Sans Arabic", value: "Noto Sans Arabic" },
  { label: "Noto Sans Hebrew", value: "Noto Sans Hebrew" },
  { label: "Noto Sans Thai", value: "Noto Sans Thai" },
  { label: "Noto Sans Devanagari", value: "Noto Sans Devanagari" },
  { label: "Noto Sans Tamil", value: "Noto Sans Tamil" },
  { label: "Noto Sans Telugu", value: "Noto Sans Telugu" },
  { label: "Noto Sans Traditional Chinese", value: "Noto Sans TC" },
  { label: "Noto Sans Simplified Chinese", value: "Noto Sans SC" },
  { label: "Noto Sans Korean", value: "Noto Sans KR" },
  { label: "Noto Sans Hong Kong", value: "Noto Sans HK" },
];
