export const source_languages = [
  { label: "Auto Detect", value: "auto" },
  { label: "Afrikaans", value: "af" },
  { label: "Arabic - العربية", value: "ar" },
  { label: "Armenian - Հայերեն", value: "hy" },
  { label: "Azerbaijani - Azərbaycan", value: "az" },
  { label: "Belarusian - Беларуская", value: "be" },
  { label: "Bosnian - Bosanski", value: "bs" },
  { label: "Bulgarian - Български", value: "bg" },
  { label: "Catalan - Català", value: "ca" },
  { label: "Chinese - 中文", value: "zh" },
  { label: "Croatian - Hrvatski", value: "hr" },
  { label: "Czech - Čeština", value: "cs" },
  { label: "Danish - Dansk", value: "da" },
  { label: "Dutch - Nederlands", value: "nl" },
  { label: "English", value: "en" },
  { label: "Estonian - Eesti", value: "et" },
  { label: "Finnish - Suomi", value: "fi" },
  { label: "French - Français", value: "fr" },
  { label: "Galician - Galego", value: "gl" },
  { label: "German - Deutsch", value: "de" },
  { label: "Greek - Ελληνικά", value: "el" },
  { label: "Hebrew - עברית", value: "he" },
  { label: "Hindi - हिन्दी", value: "hi" },
  { label: "Hungarian - Magyar", value: "hu" },
  { label: "Icelandic - Íslenska", value: "is" },
  { label: "Indonesian - Bahasa Indonesia", value: "id" },
  { label: "Italian - Italiano", value: "it" },
  { label: "Japanese - 日本語", value: "ja" },
  { label: "Kannada - ಕನ್ನಡ", value: "kn" },
  { label: "Kazakh - Қазақша", value: "kk" },
  { label: "Korean - 한국어", value: "ko" },
  { label: "Latvian - Latviešu", value: "lv" },
  { label: "Lithuanian - Lietuvių", value: "lt" },
  { label: "Macedonian - Македонски", value: "mk" },
  { label: "Malay - Bahasa Melayu", value: "ms" },
  { label: "Marathi - मराठी", value: "mr" },
  { label: "Maori - Te Reo Māori", value: "mi" },
  { label: "Nepali - नेपाली", value: "ne" },
  { label: "Norwegian - Norsk", value: "no" },
  { label: "Persian - فارسی", value: "fa" },
  { label: "Polish - Polski", value: "pl" },
  { label: "Portuguese - Português", value: "pt" },
  { label: "Romanian - Română", value: "ro" },
  { label: "Russian - Русский", value: "ru" },
  { label: "Serbian - Српски", value: "sr" },
  { label: "Slovak - Slovenčina", value: "sk" },
  { label: "Slovenian - Slovenščina", value: "sl" },
  { label: "Spanish - Español", value: "es" },
  { label: "Swahili - Kiswahili", value: "sw" },
  { label: "Swedish - Svenska", value: "sv" },
  { label: "Tagalog - Tagalog", value: "tl" },
  { label: "Tamil - தமிழ்", value: "ta" },
  { label: "Thai - ไทย", value: "th" },
  { label: "Turkish - Türkçe", value: "tr" },
  { label: "Ukrainian - Українська", value: "uk" },
  { label: "Urdu - اردو", value: "ur" },
  { label: "Vietnamese - Tiếng Việt", value: "vi" },
  { label: "Welsh - Cymraeg", value: "cy" },
];
